version: '3.3'

services:
  bot:
    build: ./bot
    restart: always
    volumes:
      - ./docker/bot/config:/bot/config
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - GOOGLE_CLIENT_EMAIL=${GOOGLE_CLIENT_EMAIL}
      - GOOGLE_PRIVATE_KEY=${GOOGLE_PRIVATE_KEY}
      - COEFONT_ACCESS_KEY=${COEFONT_ACCESS_KEY}
      - COEFONT_CLIENT_SECRET=${COEFONT_CLIENT_SECRET}
      - AFK_CHANNELS=${AFK_CHANNELS}
